import { Store, Pinia, Persist } from '../utils'

@Store
export class Shop extends Pinia {
  shopList = []
  // diy 默认布局
  defaultIndex = {
    title: '',
    pageBg: '#FBFBFB',
    headerBg: 'transparent',
    headerColor: '#fff',
    notDiy: true,
    showFooter: false,
    components: [
      {
        name: 'card',
        alias: '卡面组件',
        isBlock: true,
        showUsername: true,
        showPhone: true,
        notDiy: true,
        fixedNo: true,
        style: {
          color: '#fff',
          zIndex: '1',
          mgT: '10',
          mgB: '10',
          mgL: '10',
          mgR: '10',
          pdT: '10',
          pdB: '120',
          pdL: 15,
          pdR: '15',
          radius: '10',
          noSize: '16',
          iconSize: 50,
          iconRadius: 25,
          noAlign: 'right',
          btnBg: 'rgba(0,0,0,0.5)',
          btnColor: '#fff',
          shadow: {
            x: 0,
            y: 0,
            radius: 0,
            color: 'rgba(217, 182, 182, 1)',
          },
          codeSize: '20',
          codeRadius: '2',
          noCardNum: true,
          //"bgSize":"100% 100%"
        },
      },
      {
        name: 'memberInfo',
        alias: '会员信息组件',
        isBlock: true,
        showUserPoint: true,
        showUserLevel: true,
        showUserBalance: true,
        style: {
          bg: 'rgba(254, 254, 254, 1)',
          color: '#333',
          mgT: '10',
          mgB: '0',
          mgL: '10',
          mgR: '10',
          pdT: '10',
          pdB: '10',
          pdL: '0',
          pdR: '0',
          itemDir: 'row',
          radius: '7',
          fontSize: '15',
          shadow: {
            x: 0,
            y: 0,
            radius: '0',
            color: 'rgba(0, 0, 0, 0.45)',
          },
        },
      },
      {
        name: 'notice',
        alias: '公告组件',
        isBlock: true,
        items: [],
        style: {
          color: '#7C6A54',
          bg: 'rgba(255, 240, 217, 1)',
          zIndex: 0,
          mgT: '10',
          mgB: 0,
          mgL: '15',
          mgR: '15',
          pdT: '8',
          pdB: '8',
          pdL: '15',
          pdR: '15',
          radius: '5',
          iconSize: 50,
          iconRadius: 25,
          shadow: {
            x: 0,
            y: 0,
            radius: 0,
            color: 'transparent',
          },
          iconColor: '#D90505',
          fontSize: '13',
        },
      },
      {
        name: 'shoplist',
        alias: '门店列表组件',
        isBlock: true,
        items: [],
        title: '',
        subTitle: '列表说明',
        showSubTitle: false,
        shopType: 'current',
        style: {
          bg: '#fff',
          color: '#333',
          mgT: 10,
          mgB: 0,
          mgL: 0,
          mgR: 0,
          pdT: 10,
          pdB: 10,
          pdL: '15',
          pdR: '15',
          iconSize: '32',
          itemMg: 5,
          zIndex: 0,
          itemWidth: '100%',
          itemDir: 'row',
          itemFontSize: 16,
          shadow: {
            x: 0,
            y: 0,
            radius: 0,
            color: 'transparent',
          },
        },
      },
      {
        name: 'swiper',
        alias: '轮播组件',
        isBlock: true,
        items: [],
        title: '',
        subTitle: '',
        style: {
          bg: '#fff',
          height: '120',
          mgT: 0,
          mgB: 0,
          mgL: 0,
          mgR: 0,
          pdT: 0,
          pdB: 0,
          pdL: 0,
          pdR: 0,
          radius: 0,
          zIndex: '1',
          shadow: {
            x: 0,
            y: 0,
            radius: 0,
            color: 'transparent',
          },
        },
      },
      {
        name: 'cube',
        alias: '宫格组件',
        isBlock: true,
        items: [],
        title: '',
        subTitle: '',
        showSubTitle: false,
        style: {
          bg: '#fff',
          color: '#555',
          mgT: -5,
          mgB: 0,
          mgL: 0,
          mgR: 0,
          pdT: '15',
          pdB: '15',
          pdL: 0,
          pdR: 0,
          zIndex: 0,
          iconFontSize: 14,
          iconSize: '41',
          itemMg: 20,
          itemWidth: '33.333333333333333%',
          itemDir: 'column',
          radius: 0,
          borderColor: '#eee',
          shadow: {
            x: 0,
            y: 0,
            radius: 0,
            color: 'transparent',
          },
          itemFontSize: '15',
        },
      },
      {
        name: 'shoplist',
        alias: '门店列表组件',
        isBlock: true,
        items: [],
        title: '附近门店',
        subTitle: '',
        showSubTitle: false,
        shopType: 'near',
        style: {
          bg: '#fff',
          color: '#333',
          mgT: '10',
          mgB: '10',
          mgL: 0,
          mgR: 0,
          pdT: '16',
          pdB: 10,
          pdL: '15',
          pdR: '15',
          iconSize: '36',
          itemMg: '11',
          zIndex: 0,
          itemWidth: '100%',
          itemDir: 'row',
          itemFontSize: 16,
          shadow: {
            x: 0,
            y: 0,
            radius: 0,
            color: 'transparent',
          },
        },
      },
    ],
  }

  // 门店列表
  async getShopList(latitude?: number | string, longitude?: number | string) {
    return app
      .request({
        url: '../../web/index.php?t=0&v=v6.3.9.05&from=wxapp&c=entry&a=wxapp&m=vip_card&do=entity_store',
        data: {
          version: 'v2',
          op: 'index_list',
          index: 1,
          latitude,
          longitude,
          i: app.User.shopInfo.groupid,
        },
      })
      .then(res => {
        this.shopList = res.data
      })
  }
}
